# Generated by Django 5.1.2 on 2024-10-20 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_staff_first_name_alter_staff_last_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='entryandexit',
            unique_together=set(),
        ),
    ]
